#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: 'mcr.microsoft.com/onebranch/cbl-mariner/build:2.0' # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  DEBIAN_FRONTEND: noninteractive

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: true
      runmode: stage
      uploadToPipelineArtifacts: false
      dependsOn:
        - Build
        - Package
      artifacts:
        - drop_Package_PackageArtifacts
    globalSdl: # https://aka.ms/obpipelines/sdl
      tsa:
        enabled: false # SDL results of non-official builds aren't uploaded to TSA by default.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
    featureFlags:
      linuxEsrpSigningPreview: true      

    stages:
    - stage: Build
      jobs:
      - job: BuildAngular
        pool:
          type: linux

        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_sdl_binskim_break: true # always break the build on binskim issues, even if TSA enabled. You can disable it by setting to 'false'
          ob_sdl_roslyn_break: true
          ob_sdl_codeSignValidation_excludes: 'regex|.+(?:dll|exe|sys|ps1|ps1xml|psc1|psd1|cdxml|vbs|js|wsf)$;-:file|**\*.zip*\**'

        steps: # These steps will be run in unrestricted container's network
          - task: onebranch.pipeline.version@1
            displayName: 'Setup BuildNumber'
            inputs:
              system: 'RevisionCounter'
              major: '1'
              minor: '0'
              exclude_commit: false

          - task: NodeTool@0
            inputs:
                versionSpec: '14.18.x'
            displayName: 'Install Node.js'

          - task: npmAuthenticate@0
            inputs:
              workingFile: './AngularApp/.npmrc'

          - script: |
              cd AngularApp
              npm install
              npm run build
            displayName: 'npm install and build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'ApplensBackend/wwwroot'
              Contents: '**'
              TargetFolder: '$(ob_outputDirectory)'

      - job: BuildAngularForNationalCloud
        pool:
          type: linux

        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_sdl_binskim_break: true # always break the build on binskim issues, even if TSA enabled. You can disable it by setting to 'false'
          ob_sdl_roslyn_break: true
          ob_sdl_codeSignValidation_excludes: 'regex|.+(?:dll|exe|sys|ps1|ps1xml|psc1|psd1|cdxml|vbs|js|wsf)$;-:file|**\*.zip*\**'

        steps: # These steps will be run in unrestricted container's network
          - task: NodeTool@0
            inputs:
                versionSpec: '14.18.x'
            displayName: 'Install Node.js'

          - task: npmAuthenticate@0
            inputs:
              workingFile: './AngularApp/.npmrc'

          - script: |
              cd AngularApp
              npm install
              npm run build-ncloud-applens-prod
            displayName: 'npm install and build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'ApplensBackend/wwwroot'
              Contents: '**'
              TargetFolder: '$(ob_outputDirectory)'              

      - job: BuildApplensBackend
        pool:
          type: linux

        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
          ob_sdl_binskim_break: true # always break the build on binskim issues, even if TSA enabled. You can disable it by setting to 'false'
          ob_sdl_roslyn_break: true
          ob_sdl_codeSignValidation_excludes: 'regex|.+(?:dll|exe|sys|ps1|ps1xml|psc1|psd1|cdxml|vbs|js|wsf)$;-:file|**\*.zip*\**'
          BuildConfiguration: 'Release'

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'echo ''export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1'' >> ~/.bashrc'
                
          - task: UseDotNet@2
            displayName: 'Install DotNet'
            inputs:
              packageType: 'sdk'
              version: '6.0.x'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: 'ApplensBackend/AppLensV3.csproj'
              feedsToUse: 'config'
              nugetConfigPath: 'ApplensBackend/nuget.config'

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              projects: ApplensBackend/AppLensV3.csproj
              arguments: '--configuration $(BuildConfiguration)'

          - task: onebranch.pipeline.signing@1
            displayName: 'Signing'
            inputs:
              command: 'sign'
              signing_environment: 'azure-ado'
              signing_profile: 'internal_azure_service'
              files_to_sign: '**/*;!**/*.pdb'
              search_root: '$(Build.SourcesDirectory)/ApplensBackend/bin'              

          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              publishWebProjects: false
              projects: ApplensBackend/AppLensV3.csproj
              arguments: '--configuration $(BuildConfiguration) --output $(ob_outputDirectory) --no-build --no-restore'
              zipAfterPublish: false

    - stage: Package
      dependsOn: Build
      jobs:
      - job: PackageArtifacts
        pool:
          type: linux

        variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
          ob_outputDirectory: '$(Build.SourcesDirectory)/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts          

        steps: # These steps will be run in unrestricted container's network
        - task: DownloadBuildArtifacts@1
          displayName: 'Download Applens Client Build Artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop_Build_BuildAngular'
            downloadPath: '$(System.ArtifactsDirectory)/drop_Build_BuildAngular'

        - task: DownloadBuildArtifacts@1
          displayName: 'Download Applens Client Build Artifacts For NationalClouds'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop_Build_BuildAngularForNationalCloud'
            downloadPath: '$(System.ArtifactsDirectory)/drop_Build_BuildAngularForNationalCloud'            

        - task: DownloadBuildArtifacts@1
          displayName: 'Download Applens Backend Build Artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop_Build_BuildApplensBackend'
            downloadPath: '$(System.ArtifactsDirectory)/drop_Build_BuildApplensBackend'

        - task: CopyFiles@2
          displayName: 'Copy Backend Files to: $(System.ArtifactsDirectory)/applensdrop'
          inputs:
            SourceFolder: '$(System.ArtifactsDirectory)/drop_Build_BuildApplensBackend'
            TargetFolder: '$(System.ArtifactsDirectory)/applensdrop'

        - task: CopyFiles@2
          displayName: 'Copy Client Files to: $(System.ArtifactsDirectory)/applensdrop/ApplensBackend/wwwroot'
          inputs:
            SourceFolder: '$(System.ArtifactsDirectory)/drop_Build_BuildAngular'
            TargetFolder: '$(System.ArtifactsDirectory)/applensdrop/ApplensBackend/wwwroot'

        - task: CopyFiles@2
          displayName: 'Copy Backend Files to: $(System.ArtifactsDirectory)/applensdrop_nationalcloud'
          inputs:
            SourceFolder: '$(System.ArtifactsDirectory)/drop_Build_BuildApplensBackend'
            TargetFolder: '$(System.ArtifactsDirectory)/applensdrop_nationalcloud'

        - task: CopyFiles@2
          displayName: 'Copy Client Files to: $(System.ArtifactsDirectory)/applensdrop/ApplensBackend/wwwroot'
          inputs:
            SourceFolder: '$(System.ArtifactsDirectory)/drop_Build_BuildAngularForNationalCloud'
            TargetFolder: '$(System.ArtifactsDirectory)/applensdrop_nationalcloud/ApplensBackend/wwwroot'            

        - task: CopyFiles@2
          displayName: 'Copy ev2 root'
          inputs:
            SourceFolder: 'ServiceGroupRoot'
            Contents: '**'
            TargetFolder: '$(ob_outputDirectory)/Ev2ServiceGroupRoot'

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.ArtifactsDirectory)/applensdrop/ApplensBackend'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(ob_outputDirectory)/Ev2ServiceGroupRoot/bin/Applens.zip'
            replaceExistingArchive: true

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.ArtifactsDirectory)/applensdrop_nationalcloud/ApplensBackend'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(ob_outputDirectory)/Ev2ServiceGroupRoot/bin/ApplensNationalCloud.zip'
            replaceExistingArchive: true            

        - task: DeleteFiles@1
          inputs:
            SourceFolder: '$(System.ArtifactsDirectory)'
            Contents: |
              drop_Build_BuildApplensBackend
              drop_Build_BuildAngular
              drop_Build_BuildAngularForNationalCloud
              applensdrop